[connections.all_data1]
dialect = "mysql"
host = "127.0.0.1"
port = 3307
database = "job_db"
username = "root"
password = ""

[connections.course]
dialect = "mysql"
host = "127.0.0.1"
port = 3307
database = "job_db"
username = "root"
password = ""

[connections.youtube_data]
dialect = "mysql"
host = "127.0.0.1"
port = 3307
database = "job_db"
username = "root"
password = ""

[connections.twitter]
dialect = "mysql"
host = "127.0.0.1"
port = 3307
database = "job_db"
username = "root"
password = ""